### ISSUE TITLE
Misc chat improvements

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#110] opened 2021-02-26 20:54 UTC
- [x] URLs in chats should automatically be clickable (and should open in another tab, of course).
- [x] The buttons for changing the spacing and text size sometimes get confused on the screen with the text from the chats.  (I.e., the chat text displays over the button.)  
- [x] The colors of these buttons are so muted that the user tends to ignore them or assume that they are disabled.
- [x] As an organizer, it would occasionally be EXTREMELY useful to be able to make an announcement that I could be sure everyone will definitely see (i.e., they have to explicitly dismiss it, and it will show up when they log in, if they are not logged in when I post it).  Incidentally, this might be a partial solution to the "everybody needs to refresh" issue.
- [x] Chat notifications should say who the message is _from_
- [x] Peope with appropriate permission should be able to delete other people's messages (after saying yes to an appropriate warning)
- [x] Reaction emojis are a bit too small -- it's hard to see which emoji it is.  (The fact that they are on a middle-gray background doesn't help.  I'd rather have them larger with no background.)

**Comment by EdNutting** [comment] 2021-02-27 23:41
Announcements already work like that (when the rest of chat is working properly, which it seems to be now).

**Comment by EdNutting** [comment] 2021-02-28 00:19
Item 1 of this issue is a duplicate of #4

**Comment by EdNutting** [comment] 2021-02-28 01:31
Automatic link detection deployed in 7fcff76351817300aef75ec3a4dd16626c8ad20d

**Comment by rossng** [comment] 2021-03-08 22:57
Split to #137

**Comment by rossng** [comment] 2021-03-08 23:01
Split out remaining tasks to other issues.

**Closed by rossng** 2021-03-08 23:01 UTC
Labels: D-quick-win, Feb-W4
