### ISSUE TITLE
Don't list DMs on Rooms page

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#70] opened 2021-02-09 21:12 UTC
DMs should not be listed in the Rooms overview.  There are too many of     them, and they dilute the real information.  (And DMs are already listed     in the sidebar in a way that works pretty well.  I believe I can always     un-pin a DM channel and it will re-pin itself if it ever gets a message     posted, right?  That's all I need.  Maybe with a little bit more obvious     way to hide DMs -- a pop-up menu on their name in the sidebar, e.g.)

**Comment by galois1** [comment] 2021-02-10 21:26
(still unsure if this is the best issue to insert this comment, but here it goes)
Maybe have a button to easily navigate to the DMs, i.e.
<img width="583" alt="Screen Shot 2021-02-10 at 4 25 34 PM" src="https://user-images.githubusercontent.com/13901392/107574459-bd5dd900-6bbc-11eb-92ba-cb24c996154a.png">

**Comment by bcpierce00** [comment] 2021-02-10 21:44
Yes, this might be useful!  We do list them in the sidebar already (and
there are plans to make the sidebar open by default), but this can get
awkward if someone is subscribed to a lot of text channels.

**Comment by galois1** [comment] 2021-02-11 00:32
Maybe another idea - the sidebar is overloaded with information. Maybe adopt a strategy similar to Facebook? i.e. make a semantic distinction of items on the left sidebar, and items on the right side of the screen
![Untitled_Artwork](https://user-images.githubusercontent.com/13901392/107590644-a4fab800-6bd6-11eb-8a33-914960b97820.png)

**Comment by bcpierce00** [comment] 2021-02-11 01:54
I agree that we should move some things out of the sidebar and onto the top
of the screen.  If there's space for buttons with text on them, that seems
better (since people won't be using Clowdr every day, the UI should be more
obvious than use-all-the-time tools like slack and FB).

**Comment by EdNutting** [comment] 2021-02-26 19:49
* The original issue here has been fixed. 
* Those links on the home page are gone now, and exist only in the sidebar (so they're available from any page, rather than requiring clicking through the home page to find them).

So I'm closing this ticket as the issue is resolved.

Issue #76 is open and tracking the general inefficient use of space.

**Closed by EdNutting** 2021-02-26 19:49 UTC
Labels: tidying
