### ISSUE TITLE
Livestream video rooms: layout

### ISSUE THREAD

**Issue by crista** [clowdr-app/clowdr#51] opened 2021-02-06 18:40 UTC
There are controls for the layout of the stream, but they aren't working properly. This is quite important, or the presenters' slides are too small.

**Comment by EdNutting** [comment] 2021-02-06 18:54
@rossng has identified the cause of this. When the DB becomes overloaded, writes from the Actions Service stop working, leaving the DB state inconsistent with the Vonage video room (and UI) state. As a result, switching the layout becomes impossible because trying to update the layout state attempts to access invalid video source ids. He is working on a fix.

**Comment by EdNutting** [comment] 2021-02-26 19:46
This has been fixed by a series of backend and frontend changes over the last 2 weeks.

**Closed by EdNutting** 2021-02-26 19:46 UTC
Labels: bug
