### ISSUE TITLE
Sorted list of attendees should be displayed in column-major order

### ISSUE THREAD

**Issue by nrnrnr** [clowdr-app/clowdr#95] opened 2021-02-22 16:06 UTC
When clowdr sorts a list of names, it then displays the names in row-major order, as in this example:

````
Alice   Bob      Carol
Danny   Emily    Fred
Ginger  Harold   Joan
````

When the item to be displayed is short and wide, like text, sorted items should be displayed in column-major order, as `ls` does:

````
Alice   Danny   Ginger
Bob     Emily   Harold
Carol   Fred    Joan
````

**Comment by bcpierce00** [comment] 2021-03-09 11:49
The current behavior is ok in light of all this, IMO.

**Comment by rossng** [comment] 2021-03-09 22:04
I think I'm going to close this as wontfix for now. Still open to clever design workarounds if anyone comes up with one.

**Closed by rossng** 2021-03-09 22:04 UTC
Labels: C-enhancement, D-quick-win, S-frontend, T-user-interface

**Comment by nrnrnr** [comment] 2021-03-10 01:49
> I'm not sure this is possible due to our use of infinite paging. Since we can't load in all attendees at once, we only display a subset of each
 > column.
 > 
 > The only solutions I can see are:
 > 
 > * We could use column-major sorting within each loaded page, which would result in weird sorting. * We could resort the entire list each time new
 > entries were loaded, which would result in existing items being moved around whenever the user loaded a new page.
 > 
 > I don't think we can implement either of those. Perhaps there is a different design that I'm missing?

I don't think I understand your response (or "infinite paging").  
My web skills are pretty minimal, but if I were to tackle a problem
like this, I would try to render a single list in the DOM and then use
CSS Flexbox to lay it out in columns.  The list could be whatever
subset you like sorted by whatever criteria you like.  Would that not
work in your setting?

**Comment by bcpierce00** [comment] 2021-03-10 13:05
I think the issue is that the whole list of room participants is not
downloaded at the beginning -- it's fetched as needed when the window
scrolls.  Getting all the data (and getting updates as it changes) could be
slow/expensive for a conference with a lot of participants.

>
