### ISSUE TITLE
Visual Bug: Safari: Message Scrolling in Chat window

### ISSUE THREAD

**Issue by stefan-balke** [clowdr-app/clowdr#256] opened 2021-05-01 12:59 UTC
**Describe the bug**

No scrolling of chat messages in Safari (see screenshot).

**To Reproduce**

Write many chat messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/7326732/116783189-a200bc80-aa8d-11eb-8813-cfb2023743d4.png)

**Expected**

Same in Chrome:
![image](https://user-images.githubusercontent.com/7326732/116783225-dd02f000-aa8d-11eb-97e2-d02536f23be4.png)

**Desktop (please complete the following information):**

- OS: 10.15.7 (19H114)
- Browser Safari
- Version 14.0.2 (15610.3.7.1.10, 15610)

**Comment by rossng** [comment] 2021-05-02 18:09
Hi Stefan. Thanks for reporting this issue - I'll try to reproduce on my device.

**Comment by EdNutting** [comment] 2022-03-07 19:40
I believe I resolved this issue in late Decemeber, deployed the fix in mid January. It was caused by Safari not supporting flexbox properly and resolved by just re-implementing how we handle chat scrolling using web-2016 technologies to accommodate Apple.

**Closed by EdNutting** 2022-03-07 19:40 UTC
Labels: C-bug, A-chat, S-frontend, T-user-interface, U-soon
