### ISSUE TITLE
Sign up process fails in some cases

### ISSUE THREAD

**Issue by crista** [clowdr-app/clowdr#50] opened 2021-02-06 18:29 UTC
It's unclear what the exact sequence of events is that leads to this, but some people are still encountering problems signing up when they receive the initial invitation. The Clowdr app gets into a state that doesn't let them signup and/or accept the invitation. In some cases, they need to enter the registration code by hand, and it's not clear what that registration code is.

Hint: this may be related to the use of Safari first. Not sure.

Two action items here:

- Include the invitation code in the email, additionally to the invitation link, so that at least it's easier for people to copy it

- These issues need to be investigated, reproduced, and fixed.

**Comment by EdNutting** [comment] 2021-02-06 18:52
* The invite code is already included in the email, but we can add it in a second place if it helps
* This mostly seems to be Safari users now. We don't yet support Safari.
* We can't do anything about this without proper reproduction cases.

**Comment by rossng** [comment] 2021-03-09 15:51
I think it's likely that this is now fixed.

I'm going to close this particular issue as we don't currently have a reproduction that triggers this bug. But please open another issue if you run into the same thing again!

**Closed by rossng** 2021-03-09 15:51 UTC
Labels: C-bug, T-user-experience
