### ISSUE TITLE
Shuffle room improvements

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#102] opened 2021-02-26 20:19 UTC
- [x] The 30 second warning should count seconds down to 0.  And it should not be just the last 30 seconds -- it should start as soon as you enter the room.
- [x] Make shuffle rooms more random (e.g. by making the re-shuffler a bit reluctant to put people together who have already [recently] been together)
- [x] Do we still need this text?  "Updates every 60s - please help preserve our DB by not refreshing"

**Comment by rossng** [comment] 2021-03-08 23:44
Item 2 is a duplicate of #33

**Comment by rossng** [comment] 2021-03-09 20:59
All tasks split to specific issues.

**Closed by rossng** 2021-03-09 20:59 UTC
Labels: D-quick-win, T-user-experience
